### ISSUE TITLE
Diseño de coming soon

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#2]
Corregir el diseño para que no se confunda con un titulo, quizas presentarlo como marca de agua. ( Consultar con diseño )

![Captura de pantalla 2022-09-01 a la(s) 20 04 35](https://user-images.githubusercontent.com/864790/187899434-0d805f9e-9757-4862-be25-7f01ec9ddb04.png)

**Comment by LuDellaPerriera** [comment]
![image](https://user-images.githubusercontent.com/99200414/188756454-95d16dd7-129a-45c0-b513-154222a4e1c6.png)
