### ISSUE TITLE
Agregar texto descriptivo

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#3]
Agregar una sección para tener un texto descriptivo debajo del titulo principal (Consultar con diseño)

![Captura de pantalla 2022-09-01 a la(s) 20 06 23](https://user-images.githubusercontent.com/864790/187899690-83dbbb41-ef4b-47f1-95c6-54cf8bad60a5.png)

**Comment by LuDellaPerriera** [comment]
![image](https://user-images.githubusercontent.com/99200414/188756325-5d501252-b1ca-4345-be43-586e0fece975.png)

**Comment by joelibaceta** [comment]
@LuDellaPerriera es correcto, asi quedaria 👍
