### ISSUE TITLE
Cambiar texto

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#4]
Cambiar el texto para convertirlo en un call to action: 

- Pide tu periodo de prueba gratuito ahora 
- Prueba Groway Backoffice ... 

> Revisar texto final con @shamiracm 

![Captura de pantalla 2022-09-01 a la(s) 20 07 54](https://user-images.githubusercontent.com/864790/187899892-af8e22c8-bd59-4fe6-a795-c490405feef0.png)

**Comment by shamiracm** [comment]
https://github.com/Groway-Studio/backoffice-landing/commit/d861407df4e6ad0d8463218593b121f85ec4bf1e
https://github.com/Groway-Studio/backoffice-landing/commit/1d238d1f852b9715ec90d7dfd3a9d547ca393b43
Arreglado con los 2 commit, por favor podrian validar la informacion subida, gracias.

**Comment by shamiracm** [comment]
![Capture](https://user-images.githubusercontent.com/97897426/187955659-1d322da5-1183-4782-bd15-15ebae79a5d8.JPG)
