### ISSUE TITLE
Crear overlay de coming soon y restringir acceso, permitir solo a Peru

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#6]
Para evitar que alguien de otro pais use el sitio, crear un overlay para cuando el ip se encuentre fuera del pais

> Para fines de simplificar las pruebas, permitir que mediante un query param `debug=true` , se pueda visualizar aunque el ip no sea de Peru

**Comment by shamiracm** [comment]
Algunas opciones para el mensaje:


1.- Lo lamentamos por ahora este servicio sólo está disponible para Perú. Déjenos su correo y cuando esté disponible en su país le escribiremos, gracias.                                                                                                                                                        2.- Lo sentimos en estos momentos estamos disponibles solo para Perú, esperamos prontamente estarlo para su país, por lo cual nos gustaría que nos deje su correo para enviarle una alerta una vez estemos disponibles.
3.- Lo sentimos en estos momentos estamos disponibles solo para Perú. Déjenos su correo y cuando esté disponible en su país le escribiremos, gracias.

**Comment by shamiracm** [comment]
1.- Lo lamentamos por ahora este servicio sólo está disponible para Perú. Dejanos tu correo y te avisaremos cuando este disponible en tu país.

**Comment by joelibaceta** [comment]
@cristiandelcidd @shamiracm quizas esta bueno dejar el overlay a pantalla completa y reducir un poco mas el texto para que no se sienta que se le esta gritando al usuario ( _Las mayusculas en grande_ )
