### ISSUE TITLE
Conectar formulario de contacto con API

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#8]
Cuando un usuario envia el formulario de solicitud de prueba gratuita, este enviara un email al area administrativa para ponerse en contacto con el interesado, es importante que una vez el formulario se haya enviado enviar un mensaje de confirmacion: ( revisar con @shamiracm el texto final )

Ej: 
> Gracias por el interes en probar Groway Backoffice, pronto un ejecutivo de ventas lo contactara para poder gestionar su peticion.

## API Reference:

**Endpoint:** https://backoffice-git-main-joelibaceta.vercel.app/api/contact.py
**Method:** POST

```json
{
      "first_name": "first_name",
      "last_name": "last_name",
      "email": "email",
      "phone": "phone",
      "business_name": "business_name",
      "business_type": "business_type",
      "market_size": "market_size",
      "services_requested": ["contabilidad", "asistente virtual"]
}
```

**Comment by shamiracm** [comment]
2.-Estamos felices de que formes parte de  Groway Backoffice, pronto un ejecutivo de ventas lo contactará para poder gestionar su solicitud.
