### ISSUE TITLE
Implementar formulario de solicitud de prueba gratuita

### ISSUE THREAD

**Issue by joelibaceta** [Groway-Studio/backoffice-landing#9]
![Captura de pantalla 2022-09-01 a la(s) 20 13 27](https://user-images.githubusercontent.com/864790/187900850-e3602ea2-8136-4c8d-b8f8-229439b6c2a2.png)

Implementar el formulario para solicitar tu periodo de prueba, preguntas:

- Nombre Apellid
- Correo
- Telefono
- Tipo de negocio ( opciones: startup, empresa pequeña, freelancer, personal )
- Facturacion mensual ( 0 - 5000 soles ) ( 5 - 10000 ) ( 10000 a mas )
- Servicios de interes ( Multiples checkbox : asistente virtual, contabilidad, asesoria legal [este ultimo desactivado] )

**Comment by LuDellaPerriera** [comment]
![image](https://user-images.githubusercontent.com/99200414/188756573-60d3df72-3b9b-4450-81fd-f806467b2b16.png)
